### ISSUE TITLE
Skull In Inv Glitched

### ISSUE THREAD

**Issue by lexusjude** [SkyblockClient/SkyClient-Installer-Java#20]
I'm having this issue in which any skull that is in my inventory, whilst holding a certain item(I don't know why), causes it to bug out, turning into some distorted block. This is only happening in skyclient (I've tried vanilla mc, badlion and Optifine, they don't have the same problem), and I've legit reinstalled both Minecraft and skyclient and it hasn't worked.
![2022-05-20_22 30 03](https://user-images.githubusercontent.com/71864280/169630993-c657845c-4866-4a83-b853-881812c1c989.png)
.

**Comment by KTibow** [comment]
Please ask for support in the Discord instead of here.
