### ISSUE TITLE
Not working on linux (Crash & Buged UI)

### ISSUE THREAD

**Issue by CroissantDuNord** [SkyblockClient/SkyClient-Installer-Java#21]
Java Version: Openjdk version "17.0.3" 2022-04-19
Linux: PosOS Gnome

Screen

![image](https://user-images.githubusercontent.com/79372025/178058704-55a09a43-c235-44d4-a6d6-15fae70ce848.png)

Error (Console)
https://pastebin.com/Hy36NB1t (Waring very big error)

**Comment by OptixWolf** [comment]
Here is a fix for this:
sudo mkdir /tmpskyclient-universal-cache
There you create the folder in the root dir.
sudo chown username:group -R /tmpskyclient-universal-cache
There you set the rights for the folder that you can access it.

**Comment by KTibow** [comment]
Alternatively build it from source which has the fix.
This *should* be a fixed version: [Skyclient-Universal-Installer-2.0.2.zip](https://github.com/SkyblockClient/Skyclient-installer-Java/files/9304421/Skyclient-Universal-Installer-2.0.2.zip)
Come to the [discord](https://inv.wtf/skyclient) for support.
