### ISSUE TITLE
My Mac is buggin'

### ISSUE THREAD

**Issue by LordWolfWolf** [SkyblockClient/SkyClient-Installer-Java#31]
When I try to install Skyclient on Mac, it will not let me open the file because "This file is from an unidentified developer", can anyone help me resolve this problem? Thanks, Mat.

**Comment by KTibow** [comment]
it's a java program so run it like `java -jar [path]`
please come to the discord for further support

**Comment by Supermita10** [comment]
> When I try to install Skyclient on Mac, it will not let me open the file because "This file is from an unidentified developer", can anyone help me resolve this problem? Thanks, Mat.
Just right click and select open
