### ISSUE TITLE
java edition

### ISSUE THREAD

**Issue by recap2021** [SkyblockClient/SkyClient-Installer-Java#35]
Failed to download file.
Name: 1.8.9.jar

Filename on disk: 1.8.9.jar
Path: C:\Users\ajhot\AppData\Roaming\.minecraft\versions\1.8.9\1.8.9.jar
Exists: Nonexistent

**Comment by Weigurde** [comment]
#30

**Comment by Wyvest** [comment]
Please make a ticket at https://inv.wtf/skyclient
