### ISSUE TITLE
skyclient "failed to download"

### ISSUE THREAD

**Issue by teenkidboiboi** [SkyblockClient/SkyClient-Installer-Java#37]

**Comment by MissingNoko** [comment]
![Screenshot_46](https://github.com/SkyblockClient/SkyClient-Installer-Java/assets/135296056/b0850173-04f6-4ead-8e1e-5bae764ffa3b)
Same here...

**Comment by cngld** [comment]
Has anyone found a fix to this?

**Comment by Wyvest** [comment]
In the future please make a ticket at https://inv.wtf/skyclient
