### ISSUE TITLE
Failed to Launch on Mac

### ISSUE THREAD

**Issue by obvFabled** [SkyblockClient/SkyClient-Installer-Java#38]
When I try to open the Java installer for Skyclient, Java opens 5 minutes later stating "Skyclient failed to Launch, check console for more details"
Fixes?

**Comment by sm110101** [comment]
same issue occurring for me

**Comment by obvFabled** [comment]
> same issue occurring for me

Try running the program via terminal, it worked for me

**Comment by Wyvest** [comment]
Please make a ticket at https://inv.wtf/skyclient
