### ISSUE TITLE
"Java Application Launch Failed"

### ISSUE THREAD

**Issue by Crxmiad** [SkyblockClient/SkyClient-Installer-Java#40]
When trying to open the jar file for the first time, it opens a pop up saying "Java Application Launch Failed" and underneath it says "check console for possible error messages...." blah blah, this popup only shows the first time i open it. If i open the same jar file afterwards the background dims slightly which makes it seem like something is happening, but nothing is. 

Any help?

**Comment by dementedapple** [comment]
The same thing is happening to me please help

**Comment by Wyvest** [comment]
Please make a ticket at https://inv.wtf/skyclient
